apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GcpPubSubSource
metadata:
  name: testing-source
spec:
  gcpCredsSecret:  # A secret in the knative-sources namespace
    name: google-cloud-key
    key: key.json
  googleCloudProject: MY_GCP_PROJECT  # Replace this
  topic: eventing-test-topic
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
