apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/toshi0607/tekton-helloworld-go
          env:
            - name: TARGET
              value: "from Tekton!"
